quarkus.log.category."dev.flexmodel".level=DEBUG
# S3 不是默认存储，关闭 Dev Services 自动启动的 LocalStack 容器
quarkus.s3.devservices.enabled=false

flexmodel.datasource.dev_test.db-kind=sqlite
flexmodel.datasource.dev_test.url=jdbc:sqlite:file:database/sqlite_dev_test.db
