model f_project {
  id : String @id @default(uuid()),
  name: String,
  database_name: String,
  description?: String,
  enabled : Boolean @comment("是否启用") @default("true"),
  owner_id?: String @comment("所有者 ID"),
  created_by?: String @comment("创建人"),
  updated_by?: String @comment("更新人"),
  created_at?: DateTime @default(now()) @comment("创建时间"),
  updated_at?: DateTime @default(now()) @comment("更新时间"),
  @comment("租户")
}
model f_user {
  id : String @id @default(uuid()),
  name? : String @length("255") @comment("名称"),
  email? : String @length("255") @comment("邮箱"),
  password_hash : String @length("255") @comment("密码HASH"),
  role_ids: String @length("255") @comment("角色ID, 逗号分隔"),
  created_by?: String @comment("创建人"),
  updated_by?: String @comment("更新人"),
  created_at?: DateTime @default(now()) @comment("创建时间"),
  updated_at?: DateTime @default(now()) @comment("更新时间"),
  @index(name : "IDX_USERNAME", unique: "true", fields: [name]),
  @index(name : "IDX_EMAIL", unique: "true", fields: [email]),
  @comment("用户")
}
model f_role {
  id : String @id @unique @default(uuid()),
  name : String @length("255"),
  description? : String @length("255"),
  resource_ids?: String @length("2000") @comment("资源ID, 逗号分隔"),
  created_by?: String @comment("创建人"),
  updated_by?: String @comment("更新人"),
  created_at?: DateTime @default(now()) @comment("创建时间"),
  updated_at?: DateTime @default(now()) @comment("更新时间"),
  @index(name:"IDX_ROLE_NAME", unique: "true", fields: [name]),
  @comment("角色")
}
model f_resource {
  id: Long @id @default(autoIncrement()),
  name : String @length("255"),
  permission: String @length("255") @comment("权限标识"),
  type: String @length("100") @comment("类型, system: 系统级, platform: 项目级"),
  parent_id?: Long,
  @comment("资源")
}
model f_resource_template {
  id: Long @id @default(autoIncrement()),
  name: String @length("255"),
  permission: String @length("255") @comment("权限标识"),
  parent_id?: Long,
  @comment("资源模版")
}
model f_config {
  id : String @id @unique @default(uuid()),
  key : String @comment("名称") @length("255"),
  value? : String @length("255"),
  created_at : DateTime @default(now()),
  updated_at : DateTime @default(now()),
  @comment("配置"),
  @index(name:"IDX_CONFIG_KEY", unique: "true", fields: [key]),
  @comment("系统配置")
}
