package dev.flexmodel.codegen;

import java.io.PrintWriter;
import java.nio.file.Path;

/**
 * Generates Java enum classes based on the provided enum definitions.
 *
 * @author cjbi
 */
public class EnumGenerator extends AbstractGenerator {

    @Override
    public String getTargetFile(GenerationContext context, String targetDirectory) {
        return Path.of(targetDirectory, "enumeration", context.getEnumClass().getShortClassName() + ".java").toString();
    }

    @Override
    public void writeEnum(PrintWriter out, GenerationContext context) {
        EnumClass enumClass = context.getEnumClass();
        String className = enumClass.getShortClassName();
        var elements = enumClass.getElements();

        // Write package statement
        out.println("package " + enumClass.getPackageName() + ";");
        out.println();

        // Write class-level comments
        out.println("/**");
        if (enumClass.getComment() != null && !enumClass.getComment().isEmpty()) {
            out.println(" * " + enumClass.getComment());
        }
        out.println(" * Generated by Flexmodel Generator");
        out.println(" */");

        // Write class declaration
        out.println("public enum " + className + " {");
        out.print("    ");

        // Write enum elements
        for (int i = 0; i < elements.size(); i++) {
            out.print(elements.get(i));
            if (i < elements.size() - 1) {
                out.print(", ");
            }
        }

        out.println();
        // Close class
        out.println("}");
    }
}
