package dev.flexmodel.codegen;

import java.io.PrintWriter;
import java.nio.file.Path;

/**
 * Generates Java POJOs based on the provided model definitions.
 *
 * @author cjbi
 */
public class PojoGenerator extends AbstractGenerator {

    @Override
    public String getTargetFile(GenerationContext context, String targetDirectory) {
        return Path.of(targetDirectory, "entity", context.getModelClass().getShortClassName() + ".java").toString();
    }

    /**
     * Writes the Java class content to the PrintWriter.
     */
    @Override
    public void writeModel(PrintWriter out, GenerationContext context) {
        ModelClass modelClass = context.getModelClass();
        String className = modelClass.getShortClassName();
        var fields = modelClass.getAllFields();

        // Write package statement
        out.println("package " + modelClass.getPackageName() + ";");
        out.println();

        // Write import statements
        if (!modelClass.getImports().isEmpty()) {
            for (String importStatement : modelClass.getImports()) {
                out.println("import " + importStatement + ";");
            }
            out.println();
        }

        // Write class-level comments
        out.println("/**");
        if (modelClass.getComment() != null && !modelClass.getComment().isEmpty()) {
            out.println(" * " + modelClass.getComment());
        }
        out.println(" * Generated by Flexmodel Generator");
        out.println(" */");

        // Write class declaration
        out.println("@ModelClass(\"" + modelClass.getOriginal().getName() + "\")");
        out.println("public class " + className + " {");

        // Write field declarations
        for (ModelField field : fields) {
            out.println();
            if (field.getComment() != null && !field.getComment().isEmpty()) {
                out.println("  /**");
                out.println("   * " + field.getComment());
                out.println("   */");
            }
            if (field.isRelationField()) {
                out.println("  @ModelRelation");
            }
            out.println("  @ModelField(\"" + field.getOriginal().getName() + "\")");
            out.println("  private " + field.getShortTypeName() + " " + field.getVariableName() + ";");
        }

        // Write getter and setter methods
        for (ModelField field : fields) {
            generateGetter(out, field);
            generateSetter(out, field);
        }
        if (modelClass.getIdField() != null) {
            generateToString(out, modelClass);
            generateEquals(out, modelClass);
        }
        out.println();
        // Close class
        out.println("}");
    }

    /**
     * Generates a getter method for a given field.
     */
    private void generateGetter(PrintWriter out, ModelField field) {
        out.println();
        out.println("  public " + field.getShortTypeName() + " get" + StringUtils.capitalize(field.getVariableName()) + "() {");
        out.println("    return " + field.getVariableName() + ";");
        out.println("  }");
    }

    /**
     * Generates a setter method for a given field.
     */
    private void generateSetter(PrintWriter out, ModelField field) {
        out.println();
        out.println("  public void set" + StringUtils.capitalize(field.getVariableName()) + "(" + field.getShortTypeName() + " " + field.getVariableName() + ") {");
        out.println("    this." + field.getVariableName() + " = " + field.getVariableName() + ";");
        out.println("  }");
    }

    private void generateToString(PrintWriter out, ModelClass modelClass) {
        String idGetter = "get" + StringUtils.capitalize(modelClass.getIdField().getVariableName()) + "()";
        out.println();
        out.println("  @Override");
        out.println("  public String toString() {");
        out.println("    return this.getClass().getSimpleName() + \"<\" + " + idGetter + " + \">\";");
        out.println("  }");
    }

    private void generateEquals(PrintWriter out, ModelClass modelClass) {
        String idGetter = "get" + StringUtils.capitalize(modelClass.getIdField().getVariableName()) + "()";
        String className = modelClass.getShortClassName();
        out.println();
        out.println("  @Override");
        out.println("  public boolean equals(Object obj) {");
        out.println("    if (this." + idGetter + " != null && obj instanceof " + className + ") {");
        out.println("      return this." + idGetter + ".equals(((" + className + ") obj)." + idGetter + ");");
        out.println("    }");
        out.println("    return super.equals(obj);");
        out.println("  }");
    }
}
