package dev.flexmodel.codegen;

import dev.flexmodel.JsonUtils;
import dev.flexmodel.ModelImportBundle;

import java.io.IOException;
import java.io.PrintWriter;
import java.io.UncheckedIOException;
import java.nio.file.Path;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/**
 * Generates the schema BuildItem Java class.
 *
 * @author cjbi
 */
public class SchemaGenerator extends AbstractGenerator {

    @Override
    public String getTargetFile(GenerationContext context, String targetDirectory) {
        return Path.of(targetDirectory, StringUtils.capitalize(StringUtils.snakeToCamel(context.getSchemaName())) + ".java").toString();
    }

    /**
     * Writes the Java class content to the PrintWriter.
     */
    @Override
    public void write(PrintWriter out, GenerationContext context) {
        var modelClassList = context.getModelClassList();
        var enumClassList = context.getEnumClassList();
        String className = StringUtils.capitalize(StringUtils.snakeToCamel(context.getSchemaName()));

        out.println("package " + context.getPackageName() + ";");
        out.println();
        out.println("import dev.flexmodel.codegen.ObjectUtils;");
        out.println("import dev.flexmodel.BuildItem;");
        out.println("import dev.flexmodel.model.EntityDefinition;");
        out.println("import dev.flexmodel.model.EnumDefinition;");
        out.println("import dev.flexmodel.model.SchemaObject;");
        out.println("import dev.flexmodel.ModelImportBundle;");
      out.println("import dev.flexmodel.query.FilterExpression;");
      out.println();

      // Collect all imports from entity models' own import lists
      Set<String> allEntityImports = new LinkedHashSet<>();
      for (ModelClass model : modelClassList) {
        for (String imp : model.getImports()) {
          if (imp != null && !imp.isEmpty() && !imp.startsWith("dev.flexmodel.annotation")) {
            allEntityImports.add(imp);
          }
        }
        // Also add the entity class itself (may be needed for relation field references)
        if (model.getFullClassName() != null && !model.getFullClassName().startsWith("null.")) {
          allEntityImports.add(model.getFullClassName());
        }
      }
      for (String importType : allEntityImports) {
        out.println("import " + importType + ";");
      }

        out.println();
        out.println("import java.util.ArrayList;");
        out.println("import java.util.List;");
        out.println();

        // Write class-level comments
        out.println("/**");
        out.println(" * Generated by Flexmodel Generator");
        out.println(" */");

        out.println("public class " + className + " implements BuildItem {");

        out.println();
        out.println("  @Override");
        out.println("  public String getSchemaName() {");
        out.println("    return \"" + context.getSchemaName() + "\";");
        out.println("  }");
        out.println();

        // getSchema() method
        out.println("  @Override");
        out.println("  public List<SchemaObject> getSchema() {");
        out.println("    List<SchemaObject> list = new ArrayList<>();");
        out.println("    try {");
        try {
            writeSchemaBody(out, modelClassList, enumClassList);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
        out.println("    } catch (Exception e) {");
        out.println("      e.printStackTrace();");
        out.println("    }");
        out.println("    return list;");
        out.println("  }");
        out.println();

      // === Entity field models (zero-reflection, instance fields) ===
      // e.g.:  System.project.enabled.eq(true)
      // First pass: declare the nested field class for each entity
      for (ModelClass model : modelClassList) {
        String entityName = model.getShortClassName();
        String fieldsClassName = entityName + "Fields";
        out.println("  /** Field references for {@link " + entityName + "} */");
        out.println("  public static final class " + fieldsClassName + " {");
        for (ModelField field : model.getAllFields()) {
          String rawType = field.getShortTypeName();
          if (rawType == null || rawType.isEmpty()) {
            rawType = "Object";
          }
          String typeStr = boxType(rawType);
          String variableName = field.getVariableName();
          out.println("    public final FilterExpression<" + typeStr + "> "
            + variableName + " = new FilterExpression<>(\"" + field.getOriginal().getName() + "\");");
        }
        out.println("  }");
      }
      out.println();

      // Second pass: declare static instances, one per entity
      for (ModelClass model : modelClassList) {
        String entityName = model.getShortClassName();
        String fieldsClassName = entityName + "Fields";
        String instanceName = StringUtils.uncapitalize(entityName);
        out.println("  /** {@link " + entityName + "} field references */");
        out.println("  public static final " + fieldsClassName + " " + instanceName
          + " = new " + fieldsClassName + "();");
      }
      out.println();

        // getData() method
        out.println("  @Override");
        out.println("  @SuppressWarnings(\"all\")");
        out.println("  public List<ModelImportBundle.ImportData> getData() {");
        out.println("    List<ModelImportBundle.ImportData> list = new ArrayList<>();");
        out.println("    try {");
        try {
            writeDataBody(out, context);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
        out.println("    } catch (Exception e) {");
        out.println("      e.printStackTrace();");
        out.println("    }");
        out.println("    return list;");
        out.println("  }");

        out.println("}");
    }

    private void writeSchemaBody(PrintWriter out, List<ModelClass> modelClassList,
                                 List<EnumClass> enumClassList) throws IOException {
        for (ModelClass model : modelClassList) {
            out.println(" //  " + JsonUtils.toJsonString(model.getOriginal()) + "  ");
            out.println("      EntityDefinition " + model.getVariableName() + " = (EntityDefinition) ObjectUtils.deserialize(\"" + ObjectUtils.serialize(model.getOriginal()) + "\");");
        }
        for (EnumClass model : enumClassList) {
            out.println(" //  " + JsonUtils.toJsonString(model.getOriginal()) + "  ");
            out.println("      EnumDefinition " + model.getVariableName() + " = (EnumDefinition) ObjectUtils.deserialize(\"" + ObjectUtils.serialize(model.getOriginal()) + "\");");
        }
        for (ModelClass model : modelClassList) {
            out.println("      list.add(" + model.getVariableName() + ");");
        }
        for (EnumClass anEnum : enumClassList) {
            out.println("      list.add(" + anEnum.getVariableName() + ");");
        }
    }

    private void writeDataBody(PrintWriter out, GenerationContext context) throws IOException {
        @SuppressWarnings("unchecked")
        List<ModelImportBundle.ImportData> importDataList = context.getVariable("import_data");
        if (importDataList != null) {
            for (ModelImportBundle.ImportData item : importDataList) {
                out.println(" //  " + JsonUtils.toJsonString(item) + "  ");
                out.println("      list.add((ModelImportBundle.ImportData) ObjectUtils.deserialize(\"" + ObjectUtils.serialize(item) + "\"));");
            }
        }
    }

  /**
   * Box primitive types for use in generics (e.g. int → Integer).
   */
  private static String boxType(String type) {
    return switch (type) {
      case "int" -> "Integer";
      case "long" -> "Long";
      case "boolean" -> "Boolean";
      case "double" -> "Double";
      case "float" -> "Float";
      case "short" -> "Short";
      case "byte" -> "Byte";
      case "char" -> "Character";
      default -> type;
    };
  }

}
