services:
  mysql:
    container_name: ${CONTAINER_NAME_PREFIX}-flexmodel-mysql
    image: mysql:8.0
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/my.cnf:/etc/my.cnf
    restart: always
    ports:
      - "3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=GMT+08
    command: >
      bash -c "
      chmod 644 /etc/my.cnf
      && /entrypoint.sh mysqld
      "
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
    networks:
      - flexmodel
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  flexmodel-ui:
    container_name: ${CONTAINER_NAME_PREFIX}-flexmodel-ui
    image: cjbi/flexmodel-ui:latest
    restart: always
    ports:
      - ${NGINX_HTTP_PORT:-80}:80
    environment:
      - TZ=GMT+08
    depends_on:
      flexmodel-server:
        condition: service_started
    networks:
      - flexmodel
  flexmodel-server:
    container_name: ${CONTAINER_NAME_PREFIX}-flexmodel-server
    image: cjbi/flexmodel-server:latest
    restart: always
    ports:
      - "8080"
    environment:
      - |
        JAVA_OPTS=
        -Dfile.encoding=UTF-8
        -Duser.timezone=GMT+8
        -Dflexmodel.datasource.db-kind=mysql
        -Dflexmodel.datasource.url=jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
        -Dflexmodel.datasource.username=root
        -Dflexmodel.datasource.password=${MYSQL_ROOT_PASSWORD}

    networks:
      - flexmodel
    depends_on:
      mysql:
        condition: service_healthy

  flexmodel-sidecar:
    container_name: ${CONTAINER_NAME_PREFIX}-flexmodel-sidecar
    image: cjbi/flexmodel-sidecar:latest
    restart: always
    environment:
      - FLEXMODEL_JAVA_HOST=flexmodel-server
      - FLEXMODEL_JAVA_PORT=8080
      - FLEXMODEL_PORT=9999
      - FLEXMODEL_HOST=0.0.0.0
    networks:
      - flexmodel
    depends_on:
      - flexmodel-server
networks:
  flexmodel:
    name: ${CONTAINER_NAME_PREFIX}_flexmodel_default
    driver: bridge
